# MEV Shield Core - Open Source Configuration
version: "1.0.0"

rpc:
  ethereum:
    websocket_url: "wss://mainnet.infura.io/ws/v3/c4ac605f5f484c73b8135c6f2ad20ec0"
    http_url: "https://mainnet.infura.io/v3/c4ac605f5f484c73b8135c6f2ad20ec0"
    timeout_ms: 5000
  
  # Community providers
  fallback_providers:
    - name: "public_rpc"
      websocket_url: "wss://cloudflare-eth.com"
      http_url: "https://cloudflare-eth.com"

analytics:
  risk_engine:
    min_profit_threshold_eth: 0.01
    high_risk_slippage_percent: 3.0
    max_simulation_time_ms: 1000

api:
  port: 8765
  max_connections: 100

dex:
  routers:
    uniswap_v2: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
    sushiswap: "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F"

tokens:
  weth: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
  dai: "0x6B175474E89094C44Da98b954EedeAC495271d0F"
